version: '3.1'

services:
  app:
    image: 'exchange:latest'
    container_name: exchange
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "8080"
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/exchange"
      SPRING_DATASOURCE_USERNAME: Admin
      SPRING_DATASOURCE_PASSWORD: Admin
      DEMO_URL: "http://localhost:8080"

  postgres:
    image: 'postgres:15-alpine'
    container_name: postgres
    environment:
      POSTGRES_USER: Admin
      POSTGRES_PASSWORD: Admin
      POSTGRES_DB: exchange
      POSTGRES_PORT: 5432
      POSTGRES_HOST: postgres
    expose:
      - "5432"
    ports:
      - "5432:5432"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 3s
      retries: 3
